openapi: 3.0.0
x-stoplight:
  id: uokgggt69rzs8
info:
  title: task-api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /tasks:
    get:
      summary: タスク一覧を取得する
      tags:
        - タスク
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/task'
              examples: {}
      operationId: get-tasks
    post:
      summary: タスクを登録する
      tags:
        - タスク
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task-resource'
      operationId: post-tasks
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create-task-request'
        description: ''
  '/tasks/{task_id}':
    parameters:
      - schema:
          type: string
        name: task_id
        in: path
        required: true
    get:
      summary: タスクを取得する
      tags:
        - タスク
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/task-resource'
      operationId: get-tasks-taskId
    put:
      summary: タスクを更新する
      tags:
        - タスク
      responses:
        '204':
          description: No Content
        '422':
          $ref: '#/components/responses/422'
      operationId: put-tasks-taskId
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/create-task-request'
          application/xml:
            schema:
              $ref: ''
    delete:
      summary: タスクを削除する
      tags:
        - タスク
      responses:
        '204':
          description: No Content
      operationId: delete-tasks-taskId
components:
  schemas:
    task:
      title: task
      x-stoplight:
        id: xm0cwxd57w0hk
      x-tags:
        - タスク
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        status:
          type: string
        description:
          type: string
          nullable: true
      required:
        - id
        - name
        - status
        - description
    task-resource:
      properties:
        id:
          type: integer
          description: タスクID
          example: 1
        name:
          type: string
          description: タスク名
          example: LaravelにOpenAPIを導入する
        status:
          type: string
          enum:
            - Open
            - In Progress
            - Completed
        status_id:
          type: integer
          example: 1
        description:
          type: string
          nullable: true
          example: Laravel
      required:
        - id
        - name
        - status
        - status_id
        - description
    create-task-request:
      properties:
        name:
          type: string
        description:
          type: string
          nullable: true
        status_id:
          type: integer
      required:
        - name
        - status_id
  responses:
    '422':
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
        application/xml:
          schema:
            type: object
            properties: {}
